apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
        - name: resume-app
          image: colburnt/resume-app
          ports:
            - containerPort: 3000